### ISSUE TITLE
Cannot use import statement outside a module

### ISSUE THREAD

**Issue by vacuumdreams** [sindresorhus/atom-linter-xo#118]
For some reason, I am getting the error message in the title, and all my efforts to get rid of it failed. `xo` is a package dependency, and `"type": "module"` is set in my package.json. 

Running this on Big Sur 11.5.2, with Atom 1.58.0. 

<img width="461" alt="Screenshot 2021-09-21 at 08 53 31" src="https://user-images.githubusercontent.com/6715240/134124992-7b1f17d2-8a6a-4121-8b23-51861a59a5fb.png">

**Comment by sindresorhus** [comment]
Closing as Atom is abandoned.
