### ISSUE TITLE
Some repos lint some don't

### ISSUE THREAD

**Issue by blainsmith** [sindresorhus/atom-linter-xo#17]
I can't find the differences as to why the linter will not report errors within Atom. Running `xo` linter from the command line reports errors just fine. Disabling and reinstalling both linter and linter-xo have no effect.

Is there something that I may be missing as to why certain repos would not report errors within Atom?

I was able to get `linter-js-standard` to work just fine with the same install steps as `linter-xo` in the same repo, but xo still doesn't work. I even reinstalled Atom all together. I have no .editconfig set or any .eslintrc file.

**Comment by blainsmith** [comment]
Looks like there is a requirement to have `xo` in the `package.json` which is not clear when installing the linter for the editor.

**Comment by sindresorhus** [comment]
Yeah, that was introduced in https://github.com/sindresorhus/atom-linter-xo/pull/15. I should make it clearer. The the reason is so not to conflict with projects not using XO. Projects actually using XO will most often have it as a local dependency.

I'm curious how you're trying to use it, though?

**Comment by blainsmith** [comment]
Makes sense. I was about to convert an older repo to use it and I was just starting to edit code without installing xo first so it was never in my package.json yet. I wouldn't have noticed if I installed it first.

Thanks for clarifying!

**Comment by sindresorhus** [comment]
Alright. Clarified. Thanks for letting me know. Let me know if there's anything else that could be improved :)

**Comment by blainsmith** [comment]
Thanks! Keep up the good works. 🦄
