### ISSUE TITLE
It is indented, but says no

### ISSUE THREAD

**Issue by unluisco** [sindresorhus/atom-linter-xo#2]
I think it's basic but do not understand the error

![pruebas js - users unluisco dropbox freelance pruebas - atom 2015-08-23 20-33-40](https://cloud.githubusercontent.com/assets/6332263/9431440/06893e5c-49d7-11e5-826d-62df468e560d.png)

**Comment by sindresorhus** [comment]
You're probably using space indentation while it expects tab indentation.

**Comment by pqrkchqps** [comment]
I just load up your package and am having the same error.  I am using tabs not spaces.

**Comment by pqrkchqps** [comment]
I found that changing the Tab Type at the end of the atom settings scroll from auto to hard fixed the problem of tab characters not being detected.
