### ISSUE TITLE
Doesn't honor configuration overrides

### ISSUE THREAD

**Issue by invernizzie** [sindresorhus/atom-linter-xo#20]
xo allows to override configuration for certain paths by using the [`overrides` property](https://github.com/sindresorhus/xo#config-overrides) in configuration.

This is working for me using the `xo` CLI, but `atom-linter-xo` doesn't seem to care.

**Comment by kahlil** [comment]
I am having the same problem.

**Comment by kahlil** [comment]
This is now fixed for me via a bugfix in the newest eslint version. See also https://github.com/sindresorhus/atom-linter-xo/issues/19#issuecomment-202821782.

**Comment by mikaa123** [comment]
Hey there,

Anyone still having this problem?
I'm using `v0.14.0` of xo, the latest eslint (`v2.8.0`), and have updated `atom-linter-xo` to the latest version.

After some investigation, the problem seems to come from `xo`'s `lintText` called by `atom-linter-xo` function:

```js
exports.lintText = function (str, opts) {
	// need to grab filename here as `buildConfig` excludes unknown options for some reason
	// TODO: find a better way to handle this
	opts = opts || {};
	var filename = opts.filename;

	opts = optionsManager.preprocess(opts);
	opts = optionsManager.buildConfig(opts);

	var engine = new eslint.CLIEngine(opts);

	return engine.executeOnText(str, filename);
};
```

The `opts` passed to `eslint.CLIEngine` doesn't have the overridden config. Neither `optionsManager.preprocess` nor `optionsManager.buildConfig` merge overrides with `opts`. That could be the problem.

**Comment by sindresorhus** [comment]
// @jamestalmage

**Comment by seriema** [comment]
After I added [the correct xo override for `filename-case`](https://github.com/sindresorhus/xo/issues/133#issuecomment-234899113), I'm getting multiple exceptions:

<img width="459" alt="screenshot 2016-07-25 18 54 03" src="https://cloud.githubusercontent.com/assets/693684/17109665/37388aaa-5299-11e6-8347-be1bc35dbc78.png">

It works from the console:

     test/models/fitbit/day_test.js:1:1
     ✖    1:1   Filename is not in camel case. Rename it to dayTest.js.

**Comment by sindresorhus** [comment]
Already answered in https://github.com/sindresorhus/xo/issues/133#issuecomment-234899113.

**Comment by seriema** [comment]
@sindresorhus that's the solution I was referencing. It works with the xo CLI (the output was at the bottom of my comment above), but the Atom linter is throwing those exceptions in the screenshot.

**Comment by sindresorhus** [comment]
@seriema You're using the wrong option format. See the `xo/filename-case` docs.

Should be:

```json
"xo/filename-case": ["error", {"case": "camelCase"}]
```
