### ISSUE TITLE
Automagically fix issues from selected code

### ISSUE THREAD

**Issue by danilosampaio** [sindresorhus/atom-linter-xo#25]
It would be nice to fix code style from selected code:

![screenshot from 2016-05-03 20-30-37](https://cloud.githubusercontent.com/assets/3306249/15001897/cbf1aeb0-1171-11e6-9482-0aec31aec2f2.png)

**Comment by sindresorhus** [comment]
Why would you just want the selected code fixed? You can already run `XO: Fix` to fix the whole file.

**Comment by danilosampaio** [comment]
Maybe too specific, but there's cases that only new features are validated using XO, and legacy code are kept untouched, in order to simplify code review.

**Comment by sindresorhus** [comment]
I'd say it's too obscure of an use-case. I would want it to work on the whole file even though I might have accidentally selected some text. I've tried this before on another plugin and people kept complaining it wasn't working, just because they had some text selected.

**Comment by danilosampaio** [comment]
You're right, it's better to use `XO fix` command.
