### ISSUE TITLE
linter-xo isnt working

### ISSUE THREAD

**Issue by yaelber** [sindresorhus/atom-linter-xo#27]
Hey, for some reason linter-xo isnt working for me. I also have linter installed.

Any idea what I can do to troubleshoot? 

Thanks!

**Comment by yaelber** [comment]
Yes.

On Thu, Jul 14, 2016 at 1:22 PM, Matheus Fernandes <notifications@github.com

**Comment by trevor-allen** [comment]
Same issue. I installed xo globally along with the atom plugin and nothing is happening (no errors, no linting).
It does still work when run from the command line though.

**Comment by sindresorhus** [comment]
Do you have `xo` as a dependency/devDependency in package.json?

**Comment by trevor-allen** [comment]
@sindresorhus That appears to be the problem, thanks!

**Comment by sindresorhus** [comment]
I'll make it bold so people don't miss. We're also discussing a way to enable XO manually: https://github.com/sindresorhus/atom-linter-xo/issues/21
