### ISSUE TITLE
Support Linter Fix API

### ISSUE THREAD

**Issue by keplersj** [sindresorhus/atom-linter-xo#29]
Nuclide has added support for a Fix API which `linter` will eventually support. https://github.com/steelbrain/linter/wiki/Linter-API#fix

Could this be used to fix errors with xo?

**Comment by sindresorhus** [comment]
It's [already supported](https://github.com/sindresorhus/atom-linter-xo/blob/e42d53511324e705540e160eaab38088de730543/index.js#L51-L59), but `linter` doesn't yet make use of it. When it does it I guess it will *just* work. You can already fix though. Just run `XO: Fix` in the command-palette.

**Comment by keplersj** [comment]
Thanks! I'm still getting used to some of Nuclide's features so I must've missed it.

**Comment by Arcanemagus** [comment]
If you are using Nuclide it supposedly has support for the fix attribute, as to how you would utilize that I'm not sure as I don't use Nuclide myself.
