### ISSUE TITLE
Add link to rule documentation

### ISSUE THREAD

**Issue by jfmengels** [sindresorhus/atom-linter-xo#32]
https://github.com/AtomLinter/linter-eslint has a cool feature that shows a link to a rule's documentation (core or plugin rules):
![image](https://cloud.githubusercontent.com/assets/3869412/17970122/7e81189c-6ad5-11e6-99f1-f83159035b46.png)
In this case, `no-console` is clickable and opens http://eslint.org/docs/rules/no-console.

It would be nice to have this as well. Behind the scenes, this now uses [`eslint-rule-documentation`](https://github.com/jfmengels/eslint-rule-documentation/).

Implementation in `linter-eslint`: https://github.com/AtomLinter/linter-eslint/blob/master/src/main.js#L132-L134

**Comment by sindresorhus** [comment]
👍 Cool idea. Interested in doing a PR?

**Comment by jfmengels** [comment]
Sure. Putting it in my todo-list, not sure when I'll get to it, but yes.

**Comment by jfmengels** [comment]
I can't figure out how to actually run this and test it out, so I'm coding blindly here. Do you have any tips on that front?

**Comment by sindresorhus** [comment]
Run `apm link` from the repo and the reload Atom.
