### ISSUE TITLE
Links with "babel"

### ISSUE THREAD

**Issue by Mottie** [sindresorhus/atom-linter-xo#34]
I've started using this package and I've noticed that errors have a link.

![new-cap](https://cloud.githubusercontent.com/assets/136959/18028605/186f3032-6c49-11e6-9d3d-4702870ceac4.jpg)

In this case "babel/new-cap" in both the message panel and the tooltip points to this page - https://github.com/jfmengels/eslint-rule-documentation/blob/master/contributing.md - as if the rule doesn't exist.

I'm not using any ES6 that would require [babel/eslint](https://github.com/babel/babel-eslint) so that link should point to the ESLint docs (http://eslint.org/docs/rules/new-cap), right?

Also, it would be really nice to see an example of the `"rules"` option... it isn't blantantly obvious (or maybe I'm just dense), but seeing an example like this would have saved me about 30 minutes of searching:

``` js
"xo": {
  "esnext": true,
  "rules" : {
    "babel/new-cap": 0
  }
}
```

Note: I don't think this is related to this package, but the `"env"` rule seems to ignore the `"greasemonkey"` setting. That's the reason why I ended up disabling the "new-cap" rule.

``` js
"xo": {
  "esnext": true,
  "env" : [ "browser", "greasemonkey" ]
}
```

**Comment by sindresorhus** [comment]
XO uses Babel internally to be able to parse ES2015 even though it only enforces it with the `esnext` option. Some rules are incompatible with the ESLint defaults and require custom Babel ones. That's what you got linked to. @jfmengels Not sure how you want to handle this?

**Comment by sindresorhus** [comment]
> Also, it would be really nice to see an example of the "rules" option...

That's defined in the main XO readme and linked to from this plugin. From the readme:

> XO [config](https://github.com/sindresorhus/xo#config) should be defined in package.json.

Suggestion on how I can make that clearer without adding examples? I'm not interested in adding lots of examples in this readme. That's better documented in the XO readme.

**Comment by sindresorhus** [comment]
> Note: I don't think this is related to this package, but the "env" rule seems to ignore the "greasemonkey" setting. That's the reason why I ended up disabling the "new-cap" rule.

Can you provide the code you needed to enable the `greasemonkey` rule for? These are the globals defined for `greasemonkey`: https://github.com/sindresorhus/globals/blob/d254dcaff737bd4873cf36ba9ce25a1eb0c4b372/globals.json#L1265-L1280

**Comment by Mottie** [comment]
I didn't have the userscript available online until just now:

https://github.com/Mottie/GitHub-userscripts/blob/master/github-code-guides.user.js

I haven't updated the `package.json` because I still need to update all the other scripts in the repository, but this is what I have to add:

```js
"devDependencies": {
	"xo": "*"
},
"scripts": {
	"lint": "xo"
},
"xo": {
	"esnext": true,
	"env" : [ "browser", "greasemonkey" ],
	"rules" : {
		"no-alert": 0,
		"babel/new-cap": 0,
		"max-lines": 0
	}
}
```

**Comment by sindresorhus** [comment]
@Mottie `env` only specifies known globals for that environment. It doesn't change any of the rules.

**Comment by jfmengels** [comment]
For the `babel/new-cap` issue, the reason you got to that page was to request your help in improving the tool, by adding `eslint-plugin-babel` to the list of known plugins. I guess the introduction message is not as clear as I would have liked it to be :)

I'll add the plugin to the list, but that package does not have different documentation files for each rule (rather, everything shortly described in the README). To have the best experience possible for users, I'd really like for plugins to have that, so I'll create an issue over there to request support that. And after that issue has been responded to (either in favor or against), I'll add the support for it.

**Comment by jfmengels** [comment]
Created the issue over there: https://github.com/babel/eslint-plugin-babel/issues/92

**Comment by jfmengels** [comment]
I've created an issue in eslint-rule-documentation for the documentation part of the issue.
