### ISSUE TITLE
Does not lint files that are ignored from version control

### ISSUE THREAD

**Issue by Pysis868** [sindresorhus/atom-linter-xo#38]
We have certain assets in our Ruby of Rails project that are not included in source control, but may need to be edited occasionally.

Not sure if this was a design decision, or simply overlooked.

Opening this issue to see if it's simple enough to include, possibly with a configuration option if others do not want this enabled (although then they just never care to open those files, so it should be fine), or at least to see if this enhancement/bugfix would be in line with the project's direction.

**Comment by sindresorhus** [comment]
That's actually not this plugin's doing, but Atom Linter (the thing that runs all the linter plugins). See the "Do Not Lint Files Ignored by VCS" in the Atom Linter settings in Atom.

**Comment by Pysis868** [comment]
Had that feeling but didn't know about that setting.  It works now, thanks!

**Comment by sindresorhus** [comment]
Glad you got it working :) Let me know if you have any other feedback.
