### ISSUE TITLE
Use the local XO when available

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/atom-linter-xo#41]
Like the CLI does. Should have done this from the start. Can't remember why I didn't.

**Comment by novemberborn** [comment]
> Can't remember why I didn't.

I suspect you may have to run the linting in a child process to prevent arbitrary packages from running within the Atom security context? (Don't know much about how that all works though.)

**Comment by sindresorhus** [comment]
@novemberborn There's a dirty workaround: https://github.com/sindresorhus/atom-linter-xo/blob/f3d443b7c6fe3d4195afeecf767514e7a6e34e77/index.js#L11-L13

**Comment by novemberborn** [comment]
That avoids giving the dependency access to the Atom process?
