### ISSUE TITLE
Fix on save

### ISSUE THREAD

**Issue by AntonNiklasson** [sindresorhus/atom-linter-xo#44]
I saw in #7 that you chose not to add "fix on save". I think it would be a nice addition, any reason for not adding it?

**Comment by sindresorhus** [comment]
Sure. A good pull request would be welcomed :)

**Comment by AntonNiklasson** [comment]
I will try to put together a PR :)

**Comment by sindresorhus** [comment]
See these on how to do it:

- https://github.com/sindresorhus/atom-perfectionist/commit/701c0a2a4fe9fa02af4c105850caafa999f16ba2 (and https://github.com/sindresorhus/atom-perfectionist/commit/db1ef0a53aae47a7ef5f281f954d7e749670afec)
- https://github.com/sindresorhus/atom-esformatter/blob/36c30212b21023909d2906a1acca00f782823f99/index.js#L49-L65

**Comment by AntonNiklasson** [comment]
#45.
