### ISSUE TITLE
Disable for projects not using xo

### ISSUE THREAD

**Issue by silvenon** [sindresorhus/atom-linter-xo#5]
I have a project which doesn't use xo, but linter-xo still lints my files. Is there a way for linter-xo to detect which projects uses it? I feel like I'm missing something obvious.

**Comment by sindresorhus** [comment]
// @steelbrain

**Comment by steelbrain** [comment]
We need your ideas https://github.com/atom-community/linter/issues/744

**Comment by sylvainlap** [comment]
It should be great to add a setting in the linter-xo that allow to deactivate it if the xo key is not present in the package.json

**Comment by silvenon** [comment]
Yeah, that could be a nice middle ground.

**Comment by sheeley** [comment]
Absolutely should detect and/or be toggleable - would it be worth me sending a PR?

**Comment by djyde** [comment]
+1

**Comment by davej** [comment]
+1 for option to disable if the key is not found in the `package.json`. Currently I'm manually disabling and enabling it from Atom's preferences.
