### ISSUE TITLE
Path module throws TypeError when no package.json in current project

### ISSUE THREAD

**Issue by jwandrews** [sindresorhus/atom-linter-xo#56]
Atom displays an error notification every time a file is opened.

![screen shot 2016-11-30 at 11 30 03 am](https://cloud.githubusercontent.com/assets/7916874/20761252/5f6c17ce-b6f0-11e6-948f-aec3907dd912.png)

This seems to only happen when there is no `package.json` file in the current project.

I think this is why:
* In `lib/get-package-path.js`, when there is no `package.json` in the project `base = null`, the first `path.join()` call in `findPkg(base)` is receiving `null` as a first argument when it expects a string.

Package still works as expected, other than the annoying error notification every time a file is opened.

**Comment by marionebl** [comment]
I think this should be fixed on the current master. Could you test by doing

Anywhere:
```shell
apm develop xo
```

In your project:
```shell
atom -d .
```

**Comment by jwandrews** [comment]
@marionebl it does seem to be fixed in the current master. Will wait for the next release. 

Thanks for your help.

**Comment by sindresorhus** [comment]
@marionebl Can you do a new release? (`$apm publish patch`) I think you should have access since you have commit rights on this repo.

**Comment by marionebl** [comment]
I guess I don't have access to the atom package:

```
Preparing and tagging a new version ✓
Pushing v0.21.1 tag Username for 'https://github.com': marionebl
Password for 'https://marionebl@github.com': 
✓
Publishing linter-xo@v0.21.1 ✗
Creating new version failed: Requires authentication
```

**Comment by sindresorhus** [comment]
@marionebl Did you try `$ apm login`?

**Comment by marionebl** [comment]
@sindresorhus Yes. Taking this to gitter?
