### ISSUE TITLE
Feature request: ability to only lint on save

### ISSUE THREAD

**Issue by AlexGustafsson** [sindresorhus/atom-linter-xo#57]
#### What?
The option to only lint on save or only lint ever x seconds.

#### Why?
Personally I sometimes get distracted by all the warnings and errors when starting to type a expression. For example, beginning to write a comment will throw a warning saying that I'm not supposed to let comments end with a space, however I have not had the time to start typing anything. As a result I get presented with a error popup which sometimes throws me off.

![Example](http://i.imgur.com/bpkzAge.png)<br />

**Comment by marionebl** [comment]
I think this should be fixed on the current master. Could you test by doing

Anywhere:
```shell
apm develop xo
```

In your project:
```shell
atom -d .
```

**Comment by AlexGustafsson** [comment]
I had some misconceptions regarding the package's relation to the Linter package. Turning "Lint as you type" off in Linter's settings turned out to be what I was looking for.
