### ISSUE TITLE
Error: Failed getting range

### ISSUE THREAD

**Issue by awcross** [sindresorhus/atom-linter-xo#60]
Any time I have multiple empty lines I am getting this error (one popup for each empty line).

```
Error: Failed getting range. This is most likely an issue with ESLint. (no-multiple-empty-lines - More than 1 blank line not allowed. at 7:2)
    at selectMessageRange (/Users/alex/.atom/packages/linter-xo/lib/format.js:73:10)
    at /Users/alex/.atom/packages/linter-xo/lib/format.js:24:12
    at Array.map (native)
    at /Users/alex/.atom/packages/linter-xo/lib/format.js:19:19
```

<img width="464" alt="screen shot 2016-12-22 at 10 39 13 am" src="https://cloud.githubusercontent.com/assets/1489573/21436348/ea44b718-c832-11e6-8f7a-7088e32d1e04.png">

Installed packages:
```
atom-beautify@0.29.14
autoclose-html@0.23.0
ava@0.8.0
craft-json-snippets@1.4.0
craft-twig@0.3.2
editorconfig@2.0.5
file-icons@1.7.25
linter@1.11.18
linter-xo@0.21.2
markdown-table-formatter@2.8.4
minimap@4.25.7
```

**Comment by magnuslang** [comment]
I have the same issue..

**Comment by sindresorhus** [comment]
@marionebl Any ideas why this is happening? Seems like a problem with our logic.

**Comment by Arcanemagus** [comment]
`no-multiple-empty-lines` had a positioning bug that was [fixed](https://github.com/eslint/eslint/pull/7088) in v3.5.0 of ESLint, if `xo` is using an old enough version of ESLint it is likely still affected by this.

**Comment by sindresorhus** [comment]
It might help just reinstalling this plugin then, so you'll get a newer ESLint version.

**Comment by awcross** [comment]
Reinstalling seems to have fixed it.

**Comment by sindresorhus** [comment]
Cool

**Comment by awcross** [comment]
The issue came back after I restarted Atom. 🙁 Here's another screenshot.

<img width="467" alt="screen shot 2017-01-10 at 4 06 40 pm" src="https://cloud.githubusercontent.com/assets/1489573/21830119/8885241e-d74f-11e6-9409-e87ee6fd3f52.png">

**Comment by awcross** [comment]
Ping @sindresorhus

**Comment by sindresorhus** [comment]
Check what ESLint version is being used. Probably an outdated one.

**Comment by awcross** [comment]
Using `generator-nm` v3.0.1 and it was installing `xo` v0.16.0 and that was the problem. Once I upgraded all seems to be good now.

Thanks! 🙌🏽
