### ISSUE TITLE
Spammed with errors while working in an ignored test file

### ISSUE THREAD

**Issue by SupremeTechnopriest** [sindresorhus/atom-linter-xo#61]
| Service     | Version    |
| :--------- | :--------- |
| Atom        | 1.13.0      |
| linter-xo   | 0.21.2      |
| xo             | 0.17.1      |

The following error keeps popping up every time I work in a test file.
```
TypeError: Cannot read property 'messages' of undefined
  at /Users/rl/.atom/packages/linter-xo/lib/format.js:38:36
```

My `package.json` xo config is:

```
"xo": {
    "parser": "babel-eslint",
    "env": [
      "es6",
      "browser",
      "mocha"
    ],
    "globals": [
      "assert",
      "expect"
    ],
    "ignores": [
      "test/**",
      "dist/**"
    ],
    "rules": {
      "object-curly-spacing": [
        "error",
        "always"
      ],
      "array-bracket-spacing": [
        "error",
        "always"
      ]
    }
  },
```

XO should be ignoring my test files, yet I still get spammed with linter errors. 

![image](https://cloud.githubusercontent.com/assets/2261598/22117292/72a2588a-de41-11e6-8f16-a9d9691a0691.png)

I tried to remove `test\**` from `ignores` and it still throws errors.

**Comment by SupremeTechnopriest** [comment]
[`format.js:38`](https://github.com/sindresorhus/atom-linter-xo/blob/master/lib/format.js#L38) is a blank line. The only instance of messages I can find in `format.js` are lines [`17`](https://github.com/sindresorhus/atom-linter-xo/blob/master/lib/format.js#L17) and [`19`](https://github.com/sindresorhus/atom-linter-xo/blob/master/lib/format.js#L19).

**Comment by marionebl** [comment]
Chances are this happens in line 17, where `results` yields `undefined` on the `report` object. Any chance for you to share the contents of the affected file?

**Comment by SupremeTechnopriest** [comment]
Unfortunately, I am unable to share the content of my project as it is private.  However it's pretty easy to reproduce.  Add some `ignores` to your xo config and then work in the ignored directory in atom (write and save files).  I only see this error when working in ignored directories.  In my case it would be `test\**`. I did try to remove the ignore and got the same error.... Perhaps its an issue with the mocha env?

**Comment by SupremeTechnopriest** [comment]
looks like @sindresorhus fixed it! Any chance you can push to apm?

**Comment by sindresorhus** [comment]
> Any chance you can push to apm?

When we're ready to do another release.

**Comment by SupremeTechnopriest** [comment]
Thank you!
