### ISSUE TITLE
Support monorepo setups

### ISSUE THREAD

**Issue by marionebl** [sindresorhus/atom-linter-xo#66]
Given a directory structure as found in a lerna project

```
mono-repository
├── lerna.json
├── package.json
└── packages
    ├── a
    │   ├── index.js
    │   ├── package.json
    │   └── schema.js
    └── b
        ├── configuration
        ├── index.js
        ├── package.json
        └── readme.md
```

where the top-level manifest contains a dependency declaration to `xo`, but the nested packages do not.

## Actual
Files opened in `packages/**/*` are not linted

## Expected
Files opened in `packages/**/*` are linted

## Analysis

This is caused by [depensOnXO](https://github.com/sindresorhus/atom-linter-xo/blob/master/lib/lint.js#L58) using only the first found manifest file to check if xo is installed or not. I'd like to extend this by searching the filetree upwards for manifest files depending on xo. Thoughts? @sindresorhus

**Comment by marionebl** [comment]
Scrap this. This already works by specifying `"xo": false` in the sub repositories.

**Comment by sindresorhus** [comment]
Yup, https://twitter.com/sindresorhus/status/825273058415955968

**Comment by sindresorhus** [comment]
https://github.com/sindresorhus/xo/commit/cb63c5f3a3a27b79034b619f0915158abbefc90f
