### ISSUE TITLE
Run --fix from Atom

### ISSUE THREAD

**Issue by wmertens** [sindresorhus/atom-linter-xo#7]
Would be wonderful if `xo --fix` could be run on the current file (in a way that you can undo?) by way of menu command.

**Comment by sindresorhus** [comment]
// @steelbrain Can linter plugins do other things too, like adding commands?

**Comment by steelbrain** [comment]
@sindresorhus absolutely, linter just consumes a service in your package. You can make it do other things too. If I understand the issue correctly, the user wants `xo` to automatically correct the file with the errors. There are two simple ways to achieve this

1. Have a setting that can be turned on/off by the user and auto-correct the text
2. Have a command that user can trigger to correct the text

If you go with option 1, the change will be very small, it would be a few extra lines for option 2 though.
Here's an example of a linter correcting text in editor https://github.com/AtomLinter/linter-jscs/blob/de94ca6f93f01f9df231eef53ad6e51af0cd4566/index.js#L142-L154

**Comment by sindresorhus** [comment]
Thanks for the info @steelbrain :)

I'll go with option 2 when I have some time.

**Comment by steelbrain** [comment]
@sindresorhus I have an almost working version, I am just confused how `--fix` works, because when I do
```sh
~/.a/p/linter-xo ❯❯❯node node_modules/xo/cli.js --fix /tmp/test.js
/tmp/test.js
  1:12  error  "a" is defined but never used  no-unused-vars

/tmp/test.js
  0:0  warning  File ignored because of your .eslintignore file. Use --no-ignore to override
```
How do I get it to fix the file?
