### ISSUE TITLE
Upgrade to Linter v2

### ISSUE THREAD

**Issue by sindresorhus** [sindresorhus/atom-linter-xo#70]
Migration guide: http://steelbrain.me/linter/guides/upgrading-to-standard-linter-v2.html
API v2: http://steelbrain.me/linter/examples/standard-linter-v2.html
Linter message v2: http://steelbrain.me/linter/types/linter-message-v2.html

**Comment by Arcanemagus** [comment]
You'll likely also want to update to `atom-package-deps@^4.5.0` to bring in support for specifying a minimum version of `linter` (https://github.com/steelbrain/package-deps/pull/86).
