### ISSUE TITLE
Not activating above specific version combination

### ISSUE THREAD

**Issue by ApricumMedia** [sindresorhus/atom-linter-xo#81]
I'm having a really strange issue, for quite some time, as well: Whenever I install (or update) either the `linter-xo` module itself or just its dependency `linter` above the versions mentioned below, the linter ui element at the bottom bar does not appear and linting doesn't seem to occur.

The project during this is configured in the same way before and after the update, with `xo` listed as a dependency and working fine – due to this, I can not update any of the two modules. There are no errors in the Atom console, same for Atom and Atom Beta, since (I estimate) version 1.16.0. There are no global installations of either modules, I removed them when the Atom plugin stopped working, though now it does work *below* these versions.

**linter-xo** (sindresorhus): 0.22.0
**linter** (steelbrain): 1.11.23

**Comment by Arcanemagus** [comment]
If you update to the latest version of `linter` what does the (new since your version) `Linter: Debug` command show when you have a file you expect to run on open?

**Comment by ApricumMedia** [comment]
Good idea, I went ahead and updated *only* the (steelbrain) `linter` and left `linter-xo` on its version, seeing as "linter version 2" claims in its post-update notification that it should continue to work without required changes.

This is the debug output:
```
Platform: darwin
Atom Version: 1.19.0-beta2
Linter Version: 2.2.0
Opened file is ignored: No
Matching Linter Providers: 
  - XO
Disabled Linter Providers: 
Standard Linter Providers: 
  - XO
Indie Linter Providers: 
UI Providers: 
Ignore Glob: **/*.min.{js,css}
VCS Ignored Paths are excluded: true
Current File Scopes: 
  - *
  - source.js
  - punctuation.terminator.statement.js
```

**Comment by Arcanemagus** [comment]
Oh _interesting_, you should have been getting `linter-ui-default` installed automatically for you. I'm not sure why it wasn't, but you apparently need to install that manually to get any sort of interface to `linter`.

**Comment by ApricumMedia** [comment]
I'm going to do that then – how did it work up until that version, though? I've never had `linter-ui-default` installed before.

**Comment by Arcanemagus** [comment]
Linter v1 integrated the UI directly in the code, in Linter v2 the UI was split into a separate package that integrates as a service. This allows things like [linter-ui-plus](https://atom.io/packages/linter-ui-plus) to completely replace the UI if you so desire 😉.

**Comment by ApricumMedia** [comment]
I see, thanks Arcanemagus. While this now shows me *a* UI, it doesn't show me the `linter-xo` UI I had before – it was very pristine, with a "Project/Files" view and a green checkmark, now it's just three extremely out of place icons that don't even *match up with one another*.

APM doesn't yield much looking for linter-ui providers, is "linter-ui-plus" the name of the UI we've enjoyed in versions before 1.1.23?

**Comment by Arcanemagus** [comment]
`linter-xo` has _never_ had a UI, it is just a provider of messages for Linter.

There is nothing that currently implements a UI like the one from Linter v1, `linter-ui-default` is the current stock Linter UI and is the evolution of the Linter v1 Ui by the author. If somebody so desired they _could_ re-implement the v1 UI as a new UI provider that people could use, but nobody has.

`linter-ui-plus` is an alternative UI under development that does things different from `linter-ui-default`.

**Comment by ApricumMedia** [comment]
Wow, the developers of `linter` just **scrapped** the beautiful UI from < 1.11.23? That's unbelievable! When I click on a highlighted linter message now, there is not even a [popup as in the title page](https://github.com/sindresorhus/atom-linter-xo/raw/master/screenshot.png) anymore. Pardon my passionateness on this but.. I've always associated the look of the panel at the bottom and the highlighting with `xo`, not `linter` and visually, there's nothing left of it now.

**Comment by Arcanemagus** [comment]
The tooltips are enabled by default, if they aren't working for you please file an issue on [linter-ui-default](https://github.com/steelbrain/linter-ui-default/issues).

**Comment by ApricumMedia** [comment]
Thanks again, that clears that up, as well. Going to stay on the old versions until the replacement UIs have matured enough to be usable for a daily workflow. `linter` and `xo` originally convinced me to start using a Linter and pushed me into much more consistent coding, it's a shame that it was deconstructed in that way.
