### ISSUE TITLE
Question: is there a way to disable autofixing wihtout turning off specific rules?

### ISSUE THREAD

**Issue by kmscode** [sindresorhus/atom-linter-xo#86]
At the moment, I'm specifically looking at [no-var](https://eslint.org/docs/rules/no-var) - I'd like this to be a warning that doesn't get auto fixed so I can review manually in the linter output within Atom. But at the moment it looks like the only way to avoid autofixing is ```"no-var": "off"``` in my package.json.

Thanks in advance!

**Comment by sindresorhus** [comment]
No, that's not possible and probably never will, sorry. I don't see the point of doing a manual review up front. The auto-fixes are safe and you can review the Git diff afterward if it's important.
